algorithm: comatch
save_dir: ./saved_models/classic_cv/comatch
save_name: comatch_cifar10_6_30_2
resume: True
load_path: ./saved_models/classic_cv/comatch/comatch_cifar10_6_30_2/latest_model.pth
overwrite: True
use_tensorboard: False
epoch: 256
num_train_iter: 262144
num_eval_iter: 1024
num_labels: 30
batch_size: 64
eval_batch_size: 256
hard_label: False
p_cutoff: 0.95
contrast_p_cutoff: 0.8
contrast_loss_ratio: 1.0
ulb_loss_ratio: 1.0
proj_size: 64
queue_batch: 5
smoothing_alpha: 0.9
uratio: 7
T: 0.2
da_len: 32
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
use_epass: True
net: wrn_28_2
net_from_name: False
data_dir: ./data
dataset: cifar10_openset
train_sampler: RandomSampler
num_classes: 6
num_workers: 1
seed: 2
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10008
dist_backend: nccl
gpu: None
correlated_ood: False
dist_align: False
use_rot: False
