algorithm: supervised
save_dir: ./saved_models/classic_cv/supervised
save_name: supervised_semi_inat_3
resume: True
load_path: ./saved_models/classic_cv/supervised/supervised_semi_inat_3/latest_model.pth
overwrite: True
use_tensorboard: False
epoch: 100
num_train_iter: 102400
num_eval_iter: 1024
num_labels: 9721
batch_size: 64
eval_batch_size: 128
ema_m: 0.999
crop_ratio: 0.875
img_size: 224
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0003
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: resnet18
net_from_name: False
data_dir: ./data
dataset: semi_inat
train_sampler: RandomSampler
num_classes: 810
num_workers: 1
seed: 3
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10008
dist_backend: nccl
gpu: None
dist_align: False
da_len: 128
use_rot: False
p_cutoff: 0.95
uratio: 2
correlated_ood: False
ulb_loss_ratio: 1.0
