algorithm: iomatch
save_dir: ./saved_models/openset_cv/iomatch
save_name: iomatch_in30_p5_0
resume: True
load_path: ./saved_models/openset_cv/iomatch/iomatch_in30_p5_0/latest_model.pth
overwrite: True
use_tensorboard: False
epoch: 100
num_train_iter: 102400
num_eval_iter: 1024
num_labels: 1300
batch_size: 64
eval_batch_size: 128
p_cutoff: 0.95
q_cutoff: 0.5
ulb_loss_ratio: 1.0
dist_align: False
uratio: 2
ema_m: 0.999
crop_ratio: 0.875
img_size: 224
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0003
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: resnet18
net_from_name: False
data_dir: ./data
dataset: imagenet30
train_sampler: RandomSampler
num_classes: 20
num_workers: 1
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10008
dist_backend: nccl
gpu: None
correlated_ood: False
da_len: 32
use_rot: False
labeled_percent: p5
mb_loss_ratio: 1.0
op_loss_ratio: 1.0
