algorithm: safestudent
save_dir: ./saved_models/openset_cv/safestudent
save_name: safestudent_cifar100_50_250_0
resume: True
load_path: ./saved_models/openset_cv/safestudent/safestudent_cifar100_50_250_0/latest_model.pth
overwrite: True
use_tensorboard: False
epoch: 256
pre_epoch: 1
num_train_iter: 262144
num_eval_iter: 1024
num_labels: 250
batch_size: 64
eval_batch_size: 256
uratio: 7
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.001
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: wrn_28_2
net_from_name: False
data_dir: ./data
dataset: cifar100_openset
train_sampler: RandomSampler
num_classes: 50
num_workers: 1
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10008
dist_backend: nccl
gpu: None
correlated_ood: False
dist_align: False
da_len: 128
use_rot: False
p_cutoff: 0.95
ulb_loss_ratio: 1.0
thres1: 0.4
thres2: 0.3
lambda1: 1.0
lambda2: 0.05
