algorithm: dac
save_dir: ./saved_models/openset_cv/dac
save_name: dac_semi_inat_2
resume: True
load_path: ./saved_models/openset_cv/dac/dac_semi_inat_2/latest_model.pth
overwrite: True
use_tensorboard: False
epoch: 100
num_train_iter: 102400
num_eval_iter: 1024
num_labels: 9721
batch_size: 64
eval_batch_size: 128
hard_label: True
T: 0.5
p_cutoff: 0.6
ulb_loss_ratio: 1.0
uratio: 2
ema_m: 0.999
crop_ratio: 0.875
img_size: 224
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0003
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: resnet18
net_from_name: False
data_dir: ./data
dataset: semi_inat
train_sampler: RandomSampler
num_classes: 810
num_workers: 4
seed: 2
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10008
dist_backend: nccl
gpu: None
correlated_ood: False
c_cutoff: 0.6
use_joint: False
start_fix: 1
num_heads: 4
dist_align: False
da_len: 128
use_rot: False
proj_dim: 256
temp_d: 1.0
temp_s: 0.1
ema_alpha: 0.9
K: 256
lambda_u: 1.0
lambda_reg: 1.0
lambda_mi: 0.1
lambda_kd: 1.5
mask_type: soft
temp_w: 1.5
