algorithm: simmatch
save_dir: ./saved_models/classic_cv/simmatch
save_name: simmatch_semi_inat_3
resume: True
load_path: ./saved_models/classic_cv/simmatch/simmatch_semi_inat_3/latest_model.pth
overwrite: True
use_tensorboard: False
epoch: 100
num_train_iter: 102400
num_eval_iter: 1024
num_labels: 9721
batch_size: 64
eval_batch_size: 128
p_cutoff: 0.6
in_loss_ratio: 1.0
ulb_loss_ratio: 1.0
proj_size: 128
K: 60
da_len: 256
smoothing_alpha: 0.9
uratio: 2
T: 0.1
ema_m: 0.999
crop_ratio: 0.875
img_size: 224
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0003
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
use_epass: True
net: resnet18
net_from_name: False
data_dir: ./data
dataset: semi_inat
train_sampler: RandomSampler
num_classes: 810
num_workers: 4
seed: 3
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10008
dist_backend: nccl
gpu: None
correlated_ood: False
dist_align: False
use_rot: False
